server:
  port: 8092
  servlet:
    context-path: /tk-bank-mock-transaction
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: tk-bank-mock-transaction
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-ui
  output:
    ansi:
      enabled: always
  thymeleaf:
    check-template-location: false

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=50,expireAfterWrite=30m

  datasource:
    # CREATE DATABASE tk_bank;
    # CREATE USER bank_god WITH LOGIN PASSWORD '87654321';
    # ALTER DATABASE tk_bank OWNER TO bank_god;
    banking:
        jdbc-url: jdbc:postgresql://localhost:5432/tk_bank
        username: bank_god
        password: 87654321
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  liquibase:
      enabled: true
      change-log: classpath:db/changelog/changelog-master.yml
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/tk_bank
      user: bank_god
      password: 87654321

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,loggers,threaddump,prometheus

banking:
  autoincrement:
    cron: "0/30 * * * * ?"
    rate: 0.1